/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogo;

import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class Cartas extends javax.swing.JFrame {

    /**
     * Creates new form Cartas
     */
    private Integer count = 0;

    public Cartas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        naruto1 = new javax.swing.JLabel();
        naruto2 = new javax.swing.JLabel();
        naruto3 = new javax.swing.JLabel();
        naruto4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cartas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        naruto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cartanaruto.jpg"))); // NOI18N
        naruto1.setText("jLabel1");
        naruto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                naruto1MouseClicked(evt);
            }
        });

        naruto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cartanaruto.jpg"))); // NOI18N
        naruto2.setText("jLabel2");
        naruto2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                naruto2MouseClicked(evt);
            }
        });

        naruto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cartanaruto.jpg"))); // NOI18N
        naruto3.setText("jLabel3");
        naruto3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                naruto3MouseClicked(evt);
            }
        });

        naruto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cartanaruto.jpg"))); // NOI18N
        naruto4.setText("jLabel4");
        naruto4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                naruto4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(naruto1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(naruto2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(naruto3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(naruto4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(naruto4)
                    .addComponent(naruto3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(naruto2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(naruto1))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked

    }//GEN-LAST:event_jPanel1MouseClicked

    private void naruto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_naruto1MouseClicked

        int x = 0 + (int) (Math.random() * 3);

        if (x == 0) {
            naruto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cartak.jpg")));
            count = 0;
            JOptionPane.showMessageDialog(rootPane, "Nenhuma opção eliminada");
        } else if (x == 1) {
            naruto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/carta1.png")));
            count = 1;
            JOptionPane.showMessageDialog(rootPane, "Você eliminou uma opção");
        } else if (x == 2) {
            naruto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/carta2.png")));
            count = 2;
            JOptionPane.showMessageDialog(rootPane, "Você eliminou duas opções");
        } else if (x == 3) {
            naruto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/carta3.png")));
            count = 3;
            JOptionPane.showMessageDialog(rootPane, "Você eliminou três opções");
        }
        JogoTela.setCartas(count);
        this.setVisible(false);

    }//GEN-LAST:event_naruto1MouseClicked

    private void naruto2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_naruto2MouseClicked

        int x = 0 + (int) (Math.random() * 3);

        if (x == 0) {
            naruto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cartak.jpg")));
            count = 0;
            JOptionPane.showMessageDialog(rootPane, "Nenhuma opção eliminada");
        } else if (x == 1) {
            naruto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/carta1.png")));
            count = 1;
            JOptionPane.showMessageDialog(rootPane, "Você eliminou uma opção");
        } else if (x == 2) {
            naruto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/carta2.png")));
            count = 2;
            JOptionPane.showMessageDialog(rootPane, "Você eliminou duas opções");
        } else if (x == 3) {
            naruto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/carta3.png")));
            count = 3;
            JOptionPane.showMessageDialog(rootPane, "Você eliminou três opções");
        }
        JogoTela.setCartas(count);
        this.setVisible(false);
    }//GEN-LAST:event_naruto2MouseClicked

    private void naruto3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_naruto3MouseClicked

        int x = 0 + (int) (Math.random() * 3);

        if (x == 0) {
            naruto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cartak.jpg")));
            count = 0;
            JOptionPane.showMessageDialog(rootPane, "Nenhuma opção eliminada");
        } else if (x == 1) {
            naruto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/carta1.png")));
            count = 1;
            JOptionPane.showMessageDialog(rootPane, "Você eliminou uma opção");
        } else if (x == 2) {
            naruto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/carta2.png")));
            count = 2;
            JOptionPane.showMessageDialog(rootPane, "Você eliminou duas opções");
        } else if (x == 3) {
            naruto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/carta3.png")));
            count = 3;
            JOptionPane.showMessageDialog(rootPane, "Você eliminou três opções");
        }
        JogoTela.setCartas(count);
        this.setVisible(false);
    }//GEN-LAST:event_naruto3MouseClicked

    private void naruto4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_naruto4MouseClicked

        int x = 0 + (int) (Math.random() * 3);

        if (x == 0) {
            naruto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cartak.jpg")));
            count = 0;
            JOptionPane.showMessageDialog(rootPane, "Nenhuma opção eliminada");
        } else if (x == 1) {
            naruto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/carta1.png")));
            count = 1;
            JOptionPane.showMessageDialog(rootPane, "Você eliminou uma opção");
        } else if (x == 2) {
            naruto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/carta2.png")));
            count = 2;
            JOptionPane.showMessageDialog(rootPane, "Você eliminou duas opções");
        } else if (x == 3) {
            naruto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/carta3.png")));
            count = 3;
            JOptionPane.showMessageDialog(rootPane, "Você eliminou três opções");
        }
        JogoTela.setCartas(count);
        this.setVisible(false);
    }//GEN-LAST:event_naruto4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cartas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel naruto1;
    private javax.swing.JLabel naruto2;
    private javax.swing.JLabel naruto3;
    private javax.swing.JLabel naruto4;
    // End of variables declaration//GEN-END:variables
}
