/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogo;

import admin.RankingListagem;
import audio.Audio;
import dao.PerguntaDAO;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import modelo.JogoCompleto;
import modelo.ManipularImagem;
import modelo.jogador;
import modelo.pergunta;

/**
 *
 * @author Administrador
 */
public class JogoTela extends javax.swing.JFrame {

    private jogador jog;
    private Integer atual = 0;
    private Integer nivel;
    private Integer premio;
    private Integer errar;
    private Integer acertar = 0;
    private Integer parar;
    private CadastroTela ct;
    private static Integer cartas = 0;
    private pergunta pergres;
    private Boolean z;
    private Integer confirmar;

    public static Integer getCartas() {
        return cartas;
    }

    public static void setCartas(Integer cartas) {
        JogoTela.cartas = cartas;
    }

    List<pergunta> perguntas;

    JogoCompleto jc = new JogoCompleto();
    FimTela ft = new FimTela();

    ButtonGroup bg;

    public List<pergunta> getPerguntas() {
        return perguntas;
    }

    public void setPerguntas(List<pergunta> perguntas) {
        this.perguntas = perguntas;
    }

    public jogador getJog() {
        return jog;
    }

    public void setJog(jogador jog) {
        this.jog = jog;
    }

    pergunta perguntaatual;
    Audio audio = new Audio();
    ManipularImagem manipular = new ManipularImagem();

    public JogoTela() {
        initComponents();

        bg = new ButtonGroup();
        bg.add(opcao1);
        bg.add(opcao2);
        bg.add(opcao3);
        bg.add(opcao4);

        confirmar = 0;
        nivel = 1;

    }

    public void Cartas(Integer c) {
        if (c == 3) {
            if (perguntaatual.getCerta().equals("A")) {
                opcao2.setEnabled(false);
                opcao3.setEnabled(false);
                opcao4.setEnabled(false);
            } else if (perguntaatual.getCerta().equals("B")) {
                opcao1.setEnabled(false);
                opcao3.setEnabled(false);
                opcao4.setEnabled(false);
            } else if (perguntaatual.getCerta().equals("C")) {
                opcao1.setEnabled(false);
                opcao2.setEnabled(false);
                opcao4.setEnabled(false);
            } else if (perguntaatual.getCerta().equals("D")) {
                opcao1.setEnabled(false);
                opcao2.setEnabled(false);
                opcao3.setEnabled(false);
            }

        } else if (c == 1) {
            if (perguntaatual.getCerta().equals("A")) {

                opcao2.setEnabled(false);

            } else if (perguntaatual.getCerta().equals("B")) {
                opcao1.setEnabled(false);

            } else if (perguntaatual.getCerta().equals("C")) {

                opcao4.setEnabled(false);
            } else if (perguntaatual.getCerta().equals("D")) {

                opcao3.setEnabled(false);

            }

        } else if (c == 2) {
            if (perguntaatual.getCerta().equals("A")) {

                opcao2.setEnabled(false);
                opcao3.setEnabled(false);

            } else if (perguntaatual.getCerta().equals("B")) {
                opcao1.setEnabled(false);
                opcao4.setEnabled(false);
            } else if (perguntaatual.getCerta().equals("C")) {

                opcao2.setEnabled(false);
                opcao4.setEnabled(false);
            } else if (perguntaatual.getCerta().equals("D")) {
                opcao1.setEnabled(false);
                opcao2.setEnabled(false);

            }

        } else {
            opcao1.setEnabled(true);
            opcao2.setEnabled(true);
            opcao4.setEnabled(true);
            opcao3.setEnabled(true);

        }
        cartas = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        opcao1 = new javax.swing.JRadioButton();
        opcao2 = new javax.swing.JRadioButton();
        opcao3 = new javax.swing.JRadioButton();
        opcao4 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        btpular = new javax.swing.JButton();
        btcartas = new javax.swing.JButton();
        btparar = new javax.swing.JButton();
        btconfirmar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblerrar = new javax.swing.JLabel();
        lblparar = new javax.swing.JLabel();
        lblacertar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblnome = new javax.swing.JLabel();
        lblarquivo = new javax.swing.JLabel();
        lblpergunta = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));

        opcao1.setBackground(new java.awt.Color(255, 255, 255));
        opcao1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        opcao1.setForeground(new java.awt.Color(255, 255, 255));
        opcao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcao1ActionPerformed(evt);
            }
        });

        opcao2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        opcao2.setForeground(new java.awt.Color(255, 255, 255));
        opcao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcao2ActionPerformed(evt);
            }
        });

        opcao3.setBackground(new java.awt.Color(255, 255, 255));
        opcao3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        opcao3.setForeground(new java.awt.Color(255, 255, 255));
        opcao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcao3ActionPerformed(evt);
            }
        });

        opcao4.setBackground(new java.awt.Color(255, 255, 255));
        opcao4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        opcao4.setForeground(new java.awt.Color(255, 255, 255));
        opcao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcao4ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        btpular.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btpular.setForeground(new java.awt.Color(153, 153, 153));
        btpular.setText("Pular");
        btpular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpularActionPerformed(evt);
            }
        });

        btcartas.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btcartas.setForeground(new java.awt.Color(153, 153, 153));
        btcartas.setText("Cartas");
        btcartas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcartasActionPerformed(evt);
            }
        });

        btparar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btparar.setForeground(new java.awt.Color(153, 153, 153));
        btparar.setText("Parar");
        btparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpararActionPerformed(evt);
            }
        });

        btconfirmar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btconfirmar.setForeground(new java.awt.Color(153, 153, 153));
        btconfirmar.setText("Confirmar");
        btconfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btconfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(btpular, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btcartas, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btparar)
                .addGap(18, 18, 18)
                .addComponent(btconfirmar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btpular, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btcartas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btparar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btconfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel3.setForeground(new java.awt.Color(204, 204, 204));

        lblerrar.setText("0");

        lblparar.setText("999");

        lblacertar.setText("9999");

        jLabel6.setText("ERRAR");

        jLabel7.setText("PARAR");

        jLabel8.setText("ACERTAR");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblerrar)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(53, 53, 53))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(lblparar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblacertar)
                        .addGap(65, 65, 65))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblerrar)
                    .addComponent(lblparar)
                    .addComponent(lblacertar))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        lblnome.setBackground(new java.awt.Color(255, 0, 0));

        lblarquivo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lblpergunta.setBackground(new java.awt.Color(255, 0, 0));
        lblpergunta.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblpergunta.setForeground(new java.awt.Color(153, 153, 153));
        lblpergunta.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblNome.setBackground(new java.awt.Color(255, 0, 0));
        lblNome.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lblNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNomeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblnome, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblpergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opcao4)
                            .addComponent(opcao2)
                            .addComponent(opcao1)
                            .addComponent(opcao3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblarquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblarquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblpergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(opcao1)
                        .addGap(31, 31, 31)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblnome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(opcao2)
                                .addGap(41, 41, 41)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(opcao3)
                                .addGap(37, 37, 37)
                                .addComponent(opcao4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Começar o jogo

        ManipularImagem.exibiImagemLabel(jog.getImagem(), lblarquivo);
        jc = new JogoCompleto();
        jc.setJog(jog);
        ct = new CadastroTela();

        ///lblarquivo.setText(ct.get);
        lblNome.setText(jog.getLogin());
        // Buscar as perguntas do nível 1
        PerguntaDAO dao = new PerguntaDAO();

        premio = 15000;
        perguntas = dao.listarNivel(nivel);
        // colocar a primeira que aparece no PerguntaAtual
        perguntaatual = perguntas.get(0);

        //Exibir na tela
        lblpergunta.setText(perguntaatual.getEnunciado());
        opcao1.setText(perguntaatual.getA());
        opcao2.setText(perguntaatual.getB());
        opcao3.setText(perguntaatual.getC());
        opcao4.setText(perguntaatual.getD());

        lblacertar.setText(premio.toString());
        lblerrar.setText("0");
        lblparar.setText("0");


    }//GEN-LAST:event_formWindowOpened

    private void btpararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpararActionPerformed
        FimTela ft = new FimTela();
        jc.setJog(jog);
        jc.setGanhos(atual);
        ft.jc = jc;
        ft.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btpararActionPerformed

    private void lblNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNomeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNomeMouseClicked

    private void btconfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btconfirmarActionPerformed
        //Verificar se acertou
         perguntas.remove(0);
        confirmar++;
        PerguntaDAO dao = new PerguntaDAO();
        Audio audio = new Audio();
        ft = new FimTela();
        jc = new JogoCompleto();
        String z = "";
        Boolean acertou = false;

        if (opcao1.isSelected() == true) {
            z = "A";
            //atual = premio;
        } else if (opcao2.isSelected() == true) {
            z = "B";
            //  atual = premio;
        } else if (opcao3.isSelected() == true) {
            z = "C";
            //   atual = premio;
        } else if (opcao4.isSelected() == true) {
            z = "D";
            //   atual = premio;

        }

        atual = atual + premio;

        if (!perguntaatual.getCerta().equals(z)) {
            JOptionPane.showMessageDialog(rootPane, "Resposta errada");

            jc.setJog(jog);
            jc.setGanhos(errar);
            ft.jc = jc;
            ft.setVisible(true);
            this.setVisible(false);
        } else {
            //JOptionPane.showMessageDialog(rootPane, "Resposta certa");
            audio.tocar("certa.wav");
            acertou = true;

            if (acertou == true) {

                jc.setGanhos(acertar);

                
                if (nivel == 4 && confirmar == 5) {

                    nivel = 5;
                    perguntas = dao.listarNivel(nivel);
                    
                    
                } else if (confirmar == 5) {
                    nivel++;
                    perguntas = dao.listarNivel(nivel);
                    confirmar = 0;
                }

                if (nivel == 2) {
                    premio = 20000;
                } else if (nivel == 3) {
                    premio = 30000;
                } else if (nivel == 4) {
                    premio = 60000;
                } else if (nivel == 5 && confirmar == 6) {
                    premio = 1000000;
                    //nivel++;                   
                    if (acertou == false) {
                        errar = 0;
                        jc.setGanhos(errar);
                    } else {
                        jc.setGanhos(acertar);
                    }
                    jc.setJog(jog);
                    ft.jc = jc;
                    ft.setVisible(true);
                    this.setVisible(false);
                    return;
                }

                opcao1.setEnabled(true);
                opcao2.setEnabled(true);
                opcao3.setEnabled(true);
                opcao4.setEnabled(true);

                perguntaatual = perguntas.get(0);
               
                lblpergunta.setText(perguntaatual.getEnunciado());
                opcao1.setText(perguntaatual.getA());
                opcao2.setText(perguntaatual.getB());
                opcao3.setText(perguntaatual.getC());
                opcao4.setText(perguntaatual.getD());

                bg.clearSelection();

            }
            if(nivel==5&&confirmar==5){
                    btcartas.setEnabled(false);
                    btpular.setEnabled(false);
                    btparar.setEnabled(false);
                    atual = 0;
                    errar = 0;
                    acertar = 1000000;
                    lblparar.setText(atual.toString());
                    lblerrar.setText(errar.toString());
                    lblacertar.setText(acertar.toString());
            } else {
            errar = atual / 2;
            acertar = premio + atual;
            lblparar.setText(atual.toString());
            lblerrar.setText(errar.toString());
            lblacertar.setText(acertar.toString());
            }
        }

    }//GEN-LAST:event_btconfirmarActionPerformed

    private void opcao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcao3ActionPerformed
        Audio audio = new Audio();
        if (opcao1.isSelected() == true || opcao2.isSelected() == true || opcao3.isSelected() == true || opcao4.isSelected() == true) {
            audio.tocar("certeza.wav");
        }
    }//GEN-LAST:event_opcao3ActionPerformed

    private void btpularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpularActionPerformed
//        PerguntaDAO dao = new PerguntaDAO();
//        ft = new FimTela();
//        jc = new JogoCompleto();
//        atual = jc.getGanhos();
//
//        //perguntas.remove(0);
        perguntas.remove(0);
        pergres = perguntas.get(0);
        perguntaatual = pergres;

        lblpergunta.setText(perguntaatual.getEnunciado());
        opcao1.setText(perguntaatual.getA());
        opcao2.setText(perguntaatual.getB());
        opcao3.setText(perguntaatual.getC());
        opcao4.setText(perguntaatual.getD());

        opcao1.setEnabled(true);
        opcao2.setEnabled(true);
        opcao3.setEnabled(true);
        opcao4.setEnabled(true);

        btpular.setEnabled(false);
    }//GEN-LAST:event_btpularActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

        Cartas(cartas);

    }//GEN-LAST:event_formWindowGainedFocus

    private void btcartasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcartasActionPerformed
        Cartas c = new Cartas();
        c.setVisible(true);
        btcartas.setEnabled(false);


    }//GEN-LAST:event_btcartasActionPerformed

    private void opcao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcao4ActionPerformed
        Audio audio = new Audio();
        if (opcao1.isSelected() == true || opcao2.isSelected() == true || opcao3.isSelected() == true || opcao4.isSelected() == true) {
            audio.tocar("certeza.wav");
        }
    }//GEN-LAST:event_opcao4ActionPerformed

    private void opcao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcao1ActionPerformed
        Audio audio = new Audio();
        if (opcao1.isSelected() == true || opcao2.isSelected() == true || opcao3.isSelected() == true || opcao4.isSelected() == true) {
            audio.tocar("certeza.wav");
        }
    }//GEN-LAST:event_opcao1ActionPerformed

    private void opcao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcao2ActionPerformed
        Audio audio = new Audio();
        if (opcao1.isSelected() == true || opcao2.isSelected() == true || opcao3.isSelected() == true || opcao4.isSelected() == true) {
            audio.tocar("certeza.wav");
        }
    }//GEN-LAST:event_opcao2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoTela.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoTela.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoTela.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoTela.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcartas;
    private javax.swing.JButton btconfirmar;
    private javax.swing.JButton btparar;
    private javax.swing.JButton btpular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblacertar;
    private javax.swing.JLabel lblarquivo;
    private javax.swing.JLabel lblerrar;
    private javax.swing.JLabel lblnome;
    private javax.swing.JLabel lblparar;
    private javax.swing.JLabel lblpergunta;
    private javax.swing.JRadioButton opcao1;
    private javax.swing.JRadioButton opcao2;
    private javax.swing.JRadioButton opcao3;
    private javax.swing.JRadioButton opcao4;
    // End of variables declaration//GEN-END:variables
}
